### ISSUE TITLE
Fail to highlight the entry that has "[]" in the thread name

### ISSUE THREAD

**Issue by leodream** [doublep/logview#2]
When there are "[", "]" in the name of a thread, logview would highlight the entry incorrectly.
![selection_165](https://cloud.githubusercontent.com/assets/2774809/10844573/7d82d272-7f3b-11e5-914a-a8bbf44027cb.png)

I guess this is a reasonable naming? Will logview support to such format?

**Comment by doublep** [comment]
Note that only one level of nested parens is allowed after this commit and the parens must match each other. I.e. `[foo [bar] baz]` is valid, but `[foo [bar baz]]` or `[foo (bar] baz]` are not and will not be seen as entry headers.
