### ISSUE TITLE
Syntax highlighting -- conflicts with whitespace-mode when buffer text is updated in any way

### ISSUE THREAD

**Issue by daemianmack** [doublep/logview#22]
Hey there. I'm having an issue with syntax highlighting and I'm not sure if it's expected behavior.

#### Problem
Syntax highlighting appears to work only for the portion of the logfile visible on-screen when first applying the submode to the logfile.

When viewing a logfile in Logview mode, with `auto-revert-tail-mode` on, the file is tailed in the buffer as expected, but new lines lack syntax highlighting. 

Syntax highlighting will also be absent when navigating the buffer to older portions of the logfile.

#### To reproduce:
Load a logfile. I've tried both with a custom submode format on an application logfile, originally, and then with `/var/log/system.log`. The latter was not autodetected -- I choose a submode name of 'UNIX' and a date format of 'MMM d HH:mm:ss'.

#### Environment
GNU Emacs 25.1.1 on OSX 10.11.6

Great tool, thanks!

**Comment by doublep** [comment]
I cannot reproduce this on a Debian machine. Maybe you could attach an excerpt from your logfile?

In any case, some questions:
- can you reproduce this with any logfile, or only with some?
- is `auto-revert-tail-mode` important? can you, for example, see the same problem with `g` command in the mode itself?
- do you see anything suspicious in `*Messages*` buffer?
- can you reproduce with `emacs -q` or `emacs -Q` (note that you have to load Logview manually in these modes)?

**Comment by daemianmack** [comment]
Ah, so this _is_ unexpected. Good news! `PEBCAK` is the best kind of `P`.

> can you reproduce this with any logfile, or only with some?

All the ones I've tried.

> is auto-revert-tail-mode important? can you, for example, see the same problem with g command in the mode itself?

I see the same problem with the `g` command.

> do you see anything suspicious in *Messages* buffer?

No.

> can you reproduce with emacs -q or emacs -Q

I _can't_, so looks like the issue is central to something in my config. I'll try to narrow it down and post back what I find in case it's helpful to anyone.

**Comment by daemianmack** [comment]
The culprit appears to be `whitespace-mode`. If I block it from affecting the file, I get the proper faces.

Oddly, it appears that even toggling `whitespace-mode` on for the log buffer and then toggling it off results in incorrect faces.

1. Launch Emacs with `whitespace-mode` disabled. Logview buffer has correct faces...
```
There are text properties here:
  face                 (logview-timestamp logview-information-entry)
  invisible            (logview:INFO)
```

2. Enable `whitespace-mode` for the buffer, removing `logview` syntax highlighting.
```
There are text properties here:
  face                 (whitespace-line)
  fontified            t
  invisible            (logview:INFO)
```

3. Disable `whitespace-mode` for the buffer. Surprisingly, `logview` syntax highlighting absent.
```
There are text properties here:
  fontified            t
  invisible            (logview:INFO)
```

4. Attempting to re-apply the `logview` submode doesn't bring back the correct faces.
```
There are text properties here:
  face                 nil
  fontified            t
  invisible            nil
```

Anyway, my problem is resolved -- happy to help dig further if you're interested in the above as a potential issue.

Thanks again!

**Comment by doublep** [comment]
The conflict is because of font-lock: Logview doesn't use built-in fontlocker, but instead applies faces directly. Might be triggered with some other minor mode too.

**Comment by doublep** [comment]
I believe commit 664c5d4 fixes this by side-effect.
