### ISSUE TITLE
Commands Not Assigned In read-only-mode

### ISSUE THREAD

**Issue by parhamdoustdar** [doublep/logview#25]
Hi,

I installed the package from melba, and didn't add anything to my .emacs file.

Now, when I open a file, I get a message saying that longview doesn't recognize the log format (which I expect – this is not a common log format).

However, when I do M-x read-only-mode RET, pressing characters just tells me that the buffer is read-only and can't be edited.

Am I doing something wrong?

Thanks!

**Comment by doublep** [comment]
Logview commands are activated only when buffer is read-only AND submode is recognized. Without submode they won't work anyway.

**Comment by parhamdoustdar** [comment]
Ah. I was trying to use the other really nice features this package offers, like widening and narrowing, or filtering – stuff that don't depend on severity or timestamps.

Would that be too much to implement?

**Comment by doublep** [comment]
Everything depends on the submode, including filtering, and even narrowing (it needs to know where entries start and end). Unless you can configure it to understand your logs (not necessarily fully, see `IGNORED` placeholder), the mode will be useless for you.

**Comment by parhamdoustdar** [comment]
Thanks a lot!
