### ISSUE TITLE
Thank you so much for this package

### ISSUE THREAD

**Issue by mineo** [doublep/logview#26]
I recently had to sift through insane amounts of test and system logs at work - all with nonstandard formats and absolutely no tooling support. With just a few additions to logview-additional-submodes and logview-additional-timestamp-formats this turned from blankly staring at a massive wall of text into me being able to efficiently work with, understand and mentally process those logs. You have no idea how happy you've made me with this awesome package, so I'd like to say thank you very much for it 💖 

Feel free to close this :)

**Comment by doublep** [comment]
Glad it helped.
