### ISSUE TITLE
Should not add itself to auto-mode-alist

### ISSUE THREAD

**Issue by jscheid** [doublep/logview#29]
It's not customary for modes to modify `auto-mode-alist`. Also, `auto-mode-alist` is for major modes, and yours is a minor mode.

**Comment by doublep** [comment]
> It's not customary for modes to modify auto-mode-alist.

Maybe ten years ago. All of the few modes I checked now do this. Also as a user I want something I install immediately become visible. If it doesn't, it feels broken to me.

> Also, auto-mode-alist is for major modes, and yours is a minor mode.

Oh, really.
