### ISSUE TITLE
guess-submode Option to Search Past 1st Line

### ISSUE THREAD

**Issue by erichlf** [doublep/logview#40]
It would be nice if there was an option that allows guess-submode to search past the first line in a log. Maybe even an optional numeric value that would allow this function to search up until that line? This way logview can guess logs with headers, but won't take excessively long to do so.

**Comment by doublep** [comment]
Please test if the performance is fine. You probably should do it with byte-compiled code, I guess difference can be substantial.

By default it looks at up to 10 lines now, or until it finds a suitable submode.

**Comment by erichlf** [comment]
Unfortunately 10 lines isn't enough for my logs. We have a tid to name map at the beginning of our logs, so it could be 50 lines in.

**Comment by doublep** [comment]
I don't want to make it look too deep, I fear it will be too slow. But you can always customize new variable `logview-guess-lines`, 10 is not a hardcoded value.

**Comment by erichlf** [comment]
I had a log that started after 200 lines, so I set it to 250 and it recognized the style almost instantly. I think your code is more efficient than you think.

**Comment by doublep** [comment]
In you case the first lines probably don't look anything like other log lines, so they are quickly skipped. But if I e.g. take a real log and make timestamps contain four digits after the point instead of three (so they are not matched, but still appear "promising"), it takes around 2-3 seconds with 10 lines here already.

**Comment by doublep** [comment]
I just pushed a commit that makes Logview not consider all `logview-guess-lines` if several (by default 3) look "promising", but don't yield a successful match. Please test if this is still good enough for your logs.

**Comment by erichlf** [comment]
Still works great.

**Comment by doublep** [comment]
Implemented in 0.14. I raised the default value for `logview-guess-lines` to 500, the default for `logview-max-promising-lines` remains at 3.
