### ISSUE TITLE
[Help] Unable to determine the log format

### ISSUE THREAD

**Issue by abhi18av** [doublep/logview#41]
Hi @doublep ,

Thanks for the wonderful package!

Recently, I have started analyzing the [Nextflow](https://github.com/nextflow-io/nextflow) logs, https://pastebin.com/j2sGLY7K , but I was not able to set it up with `logview`.

The logging framework used in Nextflow is `slf4j` as mentioned here 
https://github.com/nextflow-io/nextflow/blob/b3e2cdde5edc6152dbd0a38a571f0de5099ccb89/modules/nextflow/build.gradle#L24

I'd love to be able to rely upon `logview` to make my life simpler. Could you please help me out?

**Comment by doublep** [comment]
Hi,

Try adding a custom timestamp format with Java pattern `MMM-dd HH:mm:ss.SSS` to additional timestamp formats (open any log file and type `o S`).

**Comment by abhi18av** [comment]
Yup, using the following snippet I was able to get the color coding right 

```elisp

(setq logview-additional-timestamp-formats
      '(("MMM-dd HH:mm:ss.SSS"
         (java-pattern . "MMM-dd HH:mm:ss.SSS"))))

```

Is there a way I could highlight/filter based on the classnames `nextflow.processor.TaskRun` or the executor name `[AWS BATCH]` as shown below?


```log
Dec-16 19:23:44.249 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: /tmp/temp-s3-191216344016854499/.command.err


Dec-13 11:52:28.943 [AWSBatch-executor-99] DEBUG n.c.aws.batch.AwsBatchTaskHandler - [AWS BATCH] submitted > job=88093aec-c635-4bf8-ae92-20c4052a80ba; work-dir=s3://cape-results-gds/_nextflow/runs/f0/6d817eccba5b19abca6d0410801fc1


```

**Comment by abhi18av** [comment]
Actually, I have now understood how filtering works and this is brilliant!

Thanks mate for working on this package. I'm closing this issue as it's now resolved.
