### ISSUE TITLE
Can't get entries to be matched

### ISSUE THREAD

**Issue by anonimitoraf** [doublep/logview#42]
I've set up the following:

Date format:
![image](https://user-images.githubusercontent.com/15933322/129468538-0b356129-f156-4a10-b0e4-9b1952fbc85d.png)

Filter:
![image](https://user-images.githubusercontent.com/15933322/129468544-1ecbdd90-5dc5-4266-9564-0d9d34fdea36.png)

Highlight `test` view: 
![image](https://user-images.githubusercontent.com/15933322/129468552-4710cc72-2776-4ca7-8c0f-734a1d5a29c5.png)

Despite the above, no highlighting happens
![image](https://user-images.githubusercontent.com/15933322/129468574-7a82da8d-7bf6-4f5c-a95f-4fcdedae8ce5.png)

Am I doing anything wrong?

**Comment by doublep** [comment]
If submode is not recognized, nothing will work: views, filters, and so on. The very first thing is to have submode configured. It seems you need to add an additional submode with format string "TIMESTAMP LEVEL". Default submodes do not match since they all expect thread somewhere.

**Comment by anonimitoraf** [comment]
Ah right. Thanks!
