### ISSUE TITLE
Color surrounding portions of log lines

### ISSUE THREAD

**Issue by erichlf** [doublep/logview#44]
How do I add color markers to my log format? My log lines look like:
```
[THREAD] [0m[LEVEL] [TIMESTAMP] [NAME]: MESSAGE[0m
```
The color before level is different for different levels.

**Comment by doublep** [comment]
I don't understand the question.

**Comment by erichlf** [comment]
After `[THREAD]` there is a few characters that indicate a color. The color isn't important to me, but it is making it where my format isn't recognized, because I am unsure how to ignore those characters. So my question is how to I write a format specifier that is like the above, but ignores those characters?

**Comment by doublep** [comment]
If the characters are the same in all cases, you can just include them verbatim into the format. Otherwise you can try using special placeholder `IGNORED`. Currently there is no way to restrict what exactly is ignored, it defaults to regexp `[^ \t\n]+` unless at the very end, then it is `.+`.

**Comment by erichlf** [comment]
The following doesn't seem to work.
```     
   ("MYLOG"
       (format . "[THREAD] IGNORED[LEVEL] [TIMESTAMP] [NAME]: MESSAGE")
       (levels . "MYLEVELS")
       (timestamp "MYTIME")
       (aliases)))
```

**Comment by doublep** [comment]
Post a few sample lines of your logfile.

**Comment by erichlf** [comment]
```
[lidar_calibration_server-1] [0m[INFO] [1662144144.751489669] [iris_lidar_odometry_calibration.lidar_calibration_server]: Received request to begin calibration[0m
[lidar_calibration_server-1] [0m[INFO] [1662144144.751811992] [iris_lidar_odometry_calibration.lidar_calibration_server]: Beginning calibration[0m
[lidar_calibration_server-1] [0m[INFO] [1662144144.751928645] [iris_lidar_odometry_calibration.lidar_calibration_server]: Beginning data collection and calibration[0m
[lidar_calibration_server-1] [0m[INFO] [1662144144.752141880] [iris_lidar_odometry_calibration.lidar_calibration_server]: Waiting for data to begin calibration[0m
```
Unfortunately it seems like the browser mangles this a bit.

**Comment by doublep** [comment]
Logview is confused by `[` in the part that should be ignored. The problem is that the ignored part is also supposed to be terminated by that character. As a workaround you could try something like this:

    [THREAD] �[IGNORED[LEVEL] [TIMESTAMP] [NAME]: MESSAGE"

**Comment by erichlf** [comment]
That seems to have done the trick. Thanks.
