### ISSUE TITLE
my submode is not recognized

### ISSUE THREAD

**Issue by sam-s** [doublep/logview#57]
My python logs look like this:
```
2024-10-02 10:40:03 ERROR 49060/MainThread/unicur No data for foo bar baz
2024-11-03 14:40:38 WARNING 12748/MainThread/unicur little data for: quux
2024-11-03 14:53:17 INFO 3300/MainThread/asdfasd Something something blah
```
I set `logview-additional-submodes` to
```
   '(("python"
      (format . "TIMESTAMP LEVEL NAME MESSAGE")
      (levels . "RFC 5424")
      (timestamp . "ISO 8601 datetime"))))
```
but this is always shadowed by the standard `"UNIX"` submode.

Setting `logview-std-submodes` to `nil` does not help: when I open a log file, I get a gazillion lines like
```
 ■  Warning (emacs): Unknown timestamp format ’73’
 ■  Warning (emacs): Unknown timestamp format ’73’
 ■  Warning (emacs): Unknown timestamp format ’73’
 ■  Warning (emacs): Unknown timestamp format ’73’
 ■  Warning (emacs): Unknown timestamp format ’73’
 ■  Warning (emacs): Unknown timestamp format ’73’
 ■  Warning (emacs): Unknown timestamp format ’73’
 ■  Warning (emacs): Unknown timestamp format ’73’
 ■  Warning (emacs): Unknown timestamp format ’73’
 ■  Warning (emacs): Unknown timestamp format ’73’
 ■  Warning (emacs): Unknown timestamp format ’73’
 ■  Warning (emacs): Unknown timestamp format ’73’
 ■  Warning (emacs): Unknown timestamp format ’73’
 ■  Warning (emacs): Unknown timestamp format ’73’
 ■  Warning (emacs): Unknown timestamp format ’73’
 ■  Warning (emacs): Unknown timestamp format ’73’
 ■  Warning (emacs): Unknown timestamp format ’73’
 ■  Warning (emacs): Unknown timestamp format ’73’
```
in buffer `*Warnings*` (and it takes a LONG time!) and submode is not set.

When I set it with `C-c C-c` (and I have to enter timestamp format [explicitly!](https://github.com/doublep/logview/issues/56)), I do get the nice highlighting of various messages (although it would be nice if the trailing "^M" were hidden) - thank you!

So, the bottom line: I want to be able to use my submode without `C-c C-c` and killing `logview-std-submodes`.

**Comment by doublep** [comment]
Add parens around `"ISO 8601 datetime"`, i.e. `(timestamp . ("ISO 8601 datetime"))`, then it will work. Not sure why I did it like this many years ago; it can handle "any of the following timestamp options", but has a problem if there is just one option that is not inside a list. I will make it support both variants.

**Comment by sam-s** [comment]
No change necessary, it was entirely my fault.
You might want to replace `(aliases . ("Log4j" "Log4j2" "Logback"))` with `(aliases "Log4j" "Log4j2" "Logback")` - it is more intuitive IMO.
Thank you, it works now.

**Comment by doublep** [comment]
> it was entirely my fault

I disagree. When a mistake in configuration leads to unexplained and confusing misbehavior, this is the fault of software, not its user. In this case it should either fail with an understandable error or just accept a single string as if it was a list of one string.

> You might want to replace (aliases . ("Log4j" "Log4j2" "Logback")) with (aliases "Log4j" "Log4j2" "Logback") - it is more intuitive IMO.

I'm not sure because then you'd have some entries with a dot, some without, and this is pretty difficult to notice. Though, of course, this is the same in Lisp.

> Not sure why I did it like this many years ago

I now see why: initially it was written against customization interface, where expected types are pretty strictly codified. The problem is that hardly anyone uses it, apparently. (Hard to blame, it's pretty awful and has hardly improved in years.)
