### ISSUE TITLE
Invalid function: without-restriction

### ISSUE THREAD

**Issue by mwanderman** [doublep/logview#58]
I just installed logview from MELPA but it runs into a problem when I try to activate it. I get this message:
```
Logview: loaded locale timestamp formats from ‘~/.emacs.d/logview-cache.extmap’
Error during redisplay: (jit-lock-function 1) signaled (invalid-function without-restriction) [3 times]
helm-M-x-execute-command: Invalid function: without-restriction
```
The logs show some highlighting, but every time I try to take an action in the buffer I get `Invalid function: without-restriction`

`emacs-version` gives GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.15.10, Xaw scroll bars) of 2022-07-05

**Comment by doublep** [comment]
Should hopefully be fixed in 0.19.1 (will be available from MELPA in a few hours).

Reopen this bug if there are still problems with installation.

**Comment by archit-rastogi** [comment]
Getting below error:

With 0.9.12, shoul we reopen or file new bug ?

```
Debugger entered--Lisp error: (void-function internal--without-restriction)
  internal--without-restriction(#f(compiled-function () #<bytecode 0x1490708948f67e19>) long-line-optimizations-in-fontification-functions)
  logview--do-temporarily-widening(#f(compiled-function () #<bytecode -0x857d47325b73f2b>))
  logview--exiting-mode()
  kill-all-local-variables()
  normal-mode(t)
  after-find-file(nil nil t nil nil)
  revert-buffer--default(t nil)
  revert-buffer(t)
  funcall-interactively(revert-buffer t)
  call-interactively(revert-buffer nil nil)
  command-execute(revert-buffer)
```

**Comment by doublep** [comment]
Which Emacs version is that? Is Logview freshly installed or did you e.g. upgrade Emacs with it already installed?
